version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      go-modules:
        patterns:
          - "*"
    labels:
      - dependencies
      - go

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"
    ignore:
      - dependency-name: "liatrio/liatrio-gh-autogov-workflows"
    labels:
      - dependencies
      - github-actions
