---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: autogov
  description: A unified CLI for attestation verification and release management
  annotations:
    github.com/project-slug: liatrio/autogov
  tags:
    - automated-governance
    - autogov
    - golang
    - cli-app
spec:
  owner: "group:default/tag-autogov"
  lifecycle: in-progress
  type: cli-app
