name: Build Entrypoint Caller Workflow

on:
  workflow_dispatch:
  push:
    branches: ['**']
    paths-ignore:
      - .github/workflows/wf-slack-alert.yaml
      - README.md
      - CONTRIBUTING.md
      - catalog-info.yaml
      - renovate.json
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]

permissions: {}

jobs:
  attest-blob-hp: #blob
    if: github.event.pull_request.draft == false
    permissions:
      id-token: write
      attestations: write
      packages: read
      contents: write
      actions: read
    uses: liatrio/liatrio-gh-autogov-workflows/.github/workflows/rw-hp-build-blob.yaml@5d928589d9ec6c4d9a23b54da7cca19bf0a5f741 # v0.7.5
    secrets: inherit
    with:
      subject-path: |
        autogov-verify
      cert-identity: https://github.com/liatrio/liatrio-gh-autogov-workflows/.github/workflows/rw-hp-attest-blob.yaml@5d928589d9ec6c4d9a23b54da7cca19bf0a5f741 # v0.7.5
