name: Dependabot Metadata

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: read

jobs:
  fetch-metadata:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@d7267f607e9d3fb96fc2fbe83e0af444713e90b7 # v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Log update type
        run: |
          echo "Update type: ${{ steps.metadata.outputs.update-type }}"
          echo "Dependency names: ${{ steps.metadata.outputs.dependency-names }}"
